import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "歴てく　IN・SIDE",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<link rel="icon" href="/icon.svg" type="image/svg" sizes="16x16" />
			<body className={inter.className}>{children}</body>
		</html>
	);
}
